name = "GroupNumbers"
uuid = "3c80737e-c28d-49fd-9c64-d7d44b4f4ed8"
authors = ["Hiroharu Sugawara <hsugawa@gmail.com>"]
version = "0.4.0"

[deps]
FunctionWrappers = "069b7b12-0de2-55c6-9aab-29f3d0a68a2e"

[compat]
FunctionWrappers = "1.1.3"
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
